apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "locust.fullname" . }}
  labels:
    app.kubernetes.io/name: locust-master
    app.kubernetes.io/part-of: locust
    helm.sh/chart: {{ include "locust.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "locust.fullname" . }}
data:
{{ (.Files.Glob "tasks/*").AsConfig | indent 2 }}
