apiVersion: v1
kind: Service
metadata:
  name: {{ include "locust.fullname" . }}
  labels:
    app.kubernetes.io/name: locust-master
    app.kubernetes.io/part-of: locust
    helm.sh/chart: {{ include "locust.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.master.service.type }}
  ports:
  - name: http
    port: {{ .Values.master.service.externalPort }}
    targetPort: {{ .Values.master.service.internalPort }}
    protocol: TCP
  - name: master-p1
    port: 5557
    protocol: TCP
    targetPort: 5557
  - name: master-p2
    port: 5558
    protocol: TCP
    targetPort: 5558
  selector:
    app.kubernetes.io/name: locust-master
    app.kubernetes.io/part-of: locust
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: None
